# Generated by Django 5.1.6 on 2025-05-02 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_department'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='program.department'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='subjects',
            field=models.ManyToManyField(blank=True, null=True, related_name='students', to='program.subject', verbose_name='Subjects Enrolled'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='program.department'),
        ),
        migrations.AlterField(
            model_name='hodprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hods', to='program.department'),
        ),
    ]
