# Generated by Django 5.1.6 on 2025-04-29 07:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('program', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Test Name')),
                ('max_marks', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Maximum Marks')),
                ('date', models.DateField(verbose_name='Test Date')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='program.subject', verbose_name='Subject')),
            ],
            options={
                'db_table': 'api_test',
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Marks Obtained')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Completed At')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='users.studentprofile', verbose_name='Student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='assessments.test', verbose_name='Test')),
            ],
            options={
                'db_table': 'api_test_result',
            },
        ),
    ]
